server:
  port: 88

spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 159.75.4.201:8848
        username: nacos
        password: nacos
        namespace: public
    # gateway 配置
    gateway:
      routes:
        - id: member_route # 路由的唯一标识
          uri: lb://mall-member # 转发地址 lb:使用nacos中的本地负载均衡策略
          # 断言规则 用于路由规则的匹配
          predicates:
            - Path=/member/**
            # http://localhost:9001/member/login/test =>
            # http://localhost:8001/member/login/test =>
          filters:
            - StripPrefix=1 #去掉第一层
            # http://localhost:8001/login/test

        # -id: ****
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/ware/**
          filters:
            - StripPrefix=1

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/coupon/**
          filters:
            - StripPrefix=1

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
