server:
  port: 88

spring:
  application:
    name: mall-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 159.75.4.201:8848
        username: nacos
        password: nacos
        namespace: public
    # gateway 配置
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: [ "http://localhost:8001" ] # 此行配置是重点
            allowedMethods:
              - GET
              - POST
              - HEAD
              - PUT
              - DELETE
            allowedHeaders: '*'
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: member_route # 路由的唯一标识
          uri: lb://mall-member # 转发地址 lb:使用nacos中的本地负载均衡策略
          # 断言规则 用于路由规则的匹配
          predicates:
            - Path=/renren-admin/member/**
            # http://localhost:9001/member/login/test =>
            # http://localhost:8001/member/login/test =>
          filters:
            - StripPrefix=2 #去掉第一层
            # http://localhost:8001/login/test

        # -id: ****
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/renren-admin/ware/**
          filters:
            - StripPrefix=2

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/renren-admin/product/**
          filters:
            - StripPrefix=2

        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/renren-admin/coupon/**
          filters:
            - StripPrefix=2

        - id: order_route
          uri: lb://mall-order
          predicates:
            - Path=/renren-admin/order/**
          filters:
            - StripPrefix=2

        - id: admin_route
          uri: lb://mall-admin
          predicates:
            - Path=/renren-admin/**
          filters:
            - StripPrefix=0